# Generated by Django 2.1.5 on 2020-02-09 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('marks', models.IntegerField()),
                ('negativeMarks', models.IntegerField()),
                ('subject', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ResponseSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responseIs', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quizApi.Options')),
                ('responseTo', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='quizApi.Question')),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizApi.Question'),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='answer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quizApi.Question'),
        ),
    ]
