# Generated by Django 2.1.5 on 2020-02-09 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='options',
            old_name='option',
            new_name='question',
        ),
    ]
