# Generated by Django 2.1.5 on 2020-02-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0002_auto_20200209_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='choice',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
