# Generated by Django 2.1.5 on 2020-02-09 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0003_options_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='quizApi.Question'),
        ),
    ]
