# Generated by Django 2.1.5 on 2020-02-10 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0005_auto_20200209_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizApi.Question'),
        ),
        migrations.RemoveField(
            model_name='answerkey',
            name='answer',
        ),
        migrations.AddField(
            model_name='answerkey',
            name='answer',
            field=models.ManyToManyField(to='quizApi.Options'),
        ),
    ]
