# Generated by Django 2.1.5 on 2020-02-14 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0007_remove_answerkey_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerkey',
            name='question',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizApi.Question'),
        ),
    ]
