# Generated by Django 2.1.5 on 2020-02-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizApi', '0008_answerkey_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answerkey',
            name='answer',
        ),
        migrations.AddField(
            model_name='answerkey',
            name='answer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='quizApi.Options'),
        ),
    ]
